# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
root = File.expand_path("../../", __FILE__)
Solution.create(:title=>'SyntraNet', :description=>'<p>SyntraNet is an open health platform from Thrasys, Inc. designed to rapidly configure and deploy highly scalable collaborative healthcare networks.</p><p>SyntraNet provides connectivity, interoperability and collaboration along with easy to use cloud-based applications that are accessible through browsers, desktops, smart phones, pads and telepresence. </p>', :tab_title=>'Overview', :image=>File.open(root + "/picholder/technology/img_health_network.png"))
Solution.create(:title=>'Open Health Platform', :description=>'<p>SyntraNet is based on patent pending innovations for information technology aimed at networks of connected enterprises and uses state of the art architectures for XML services, user interfaces, configurable workflows, rules, and interoperability.</p><p>Core SyntraNet capabilities include services to manage unique identities for persons/patients, providers, and other resources; to interconnect applications, systems and registries with semantic mapping of content; to coordinate workflows and business processes; to implement administrative and clinical rules; and to enforce and audit access to protected information.</p><p>SyntraNet also delivers a new generation of cloud-based administrative, clinical, revenue management, departmental, and patient facing applications to enable coordinated care and open programming interfaces so third-parties can offer additional applications and services.</p>', :tab_title=>'Open Health Platform',:image=>File.open(root + "/picholder/technology/img_open_platform.png"))
Solution.create(:title=>'Coordinated Care Applications', :description=>'<p>Unlike previous generations of healthcare applications designed to automate transactions and manage specific visits or episodes of care, SyntraNet applications are designed from the ground up to coordinate the continuum of care with enhanced productivity and improved workflows.</p><p>Providers, patients, service centers and payers can access applications from anywhere and at anytime to perform a variety of tasks: register persons and patients; access and update demographic and clinical information; place orders and manage clinical workflows; implement rules with decision support; schedule local and global resources; capture charges; automate revenue cycle processes; interoperate and collaborate with other participants; and comply with requirements for quality and public health reporting.</p>', :tab_title=>'Coordinated Care Applications',:image=>File.open(root + "/picholder/technology/img_on-demand_apps.png"))
Solution.create(:title=>'Accountable Care and Medical Homes', :description=>'<p><br/>SyntraNet can be configured as a solution for accountable care organizations to coordinate care and for multi-disciplinary teams to implement medical homes for patients.<br/></p><br/></p> ', :tab_title=>'Accountable Care and Medical Homes',:image=>File.open(root + "/picholder/technology/img_accountable_care-B.png"))
Technology.create(:title=>'SyntraNet Open Health Platform', :description=>'<p>The SyntraNet Open Health Platform provides technologies and components to rapidly build and deploy highly scalable collaborative health networks that provide interoperability, connectivity and applications for communities of care providers, patients, service centers, payers and public health administrators. </p><p>SyntraNet brings patent pending innovations for information technology designed for networks of connected enterprises and implements state of the art architectures for XML services, user interfaces, configurable workflows, rules, interoperability and extensible applications.</p><p>Open application programming interfaces enable third-parties and partners to offer a growing suite of applications that can be delivered and deployed through SyntraNet.</p>', :tab_title=>'Overview',:image=>File.open(root + "/picholder/technology/img_open_health_platform-B.png"))
Technology.create(:title=>'Role-Based Application Services', :description=>'<p>Application services can be flexibly configured to support tasks and workflows for different roles within a health network physicians, nurses, laboratory technicians, pharmacists, patients, front-office personnel, schedulers, system administrators, and so on.</p><p>Some of the application services provided by SyntraNet include capabilities to exchange information, coordinate workflows and interoperate; create and manage unique identities (persons, physicians and other resources); register persons/patients and check-in visits; access and update demographic and clinical information information; place orders and manage clinical workflows; implement rules with decision support; schedule local and global resources; capture charges; automate revenue cycle processes; send alerts and notifications; and comply with requirements for quality and public health reporting.</p><p>Application services can be configured to function as a health information exchange; an on-demand EHR/practice management solution for physician practices; a patient portal; extension applications for hospitals; analytics solutions for population health management; and so on.</p>', :tab_title=>'Role Based Services',:image=>File.open(root + "/picholder/technology/img_roled-based_app_services.png"))
Technology.create(:title=>'Multi-Enterprise Information Model', :description=>'<p>Unlike earlier generations of healthcare solutions, SyntraNet is designed from the ground up for networks of connected enterprises.  Enterprises are modeled as nodes in a connected network with varying degrees of relationship among network participants much like a complex social network for enterprises.</p><p>In the simplest case, a SyntraNet network can be defined as a single, vertically integrated enterprise the usual model in traditional enterprise applications.  A somewhat more complex SyntraNet network is a collection of enterprises that are independent of one another a configuration equivalent to "multi-tenancy" applications.  And SyntraNet networks can be also configured to define considerably more complex topologies than multi-tenancy with hierarchies of organizations with varying degrees of relationship among participants.</p><p>With SyntraNet, applications are targeted at an entire health network with fine-grained control over data, processes, configuration and security for each participant.  The SyntraNet information and application model are unique to the industry and a new foundation for connected health information technology.</p>', :tab_title=>'Enterprise Model',:image=>File.open(root + "/picholder/technology/img_multi-enterprise_model.png"))
Technology.create(:title=>'Configurable, Scalable XML Services', :description=>'<p>From elementary CRUD (create, read, update, delete) services to high level platform and application services, all SyntraNet platform and application services are delivered as internationalized, configurable and scalable XML services deployed in the cloud.</p><p>Internationalized services support users from different locales to use applications with locale specific behaviorscreen layout, text input and edits, reference data, sorting policies, calendaring systems, currency formats, and so on.</p><p>Configurable services use metadata to define functionalityfor example, the "Register New Patient" service can function differently for different network participants based on configuration.   Services are assembled as sequences of pre-defined message request handlers to enable rapid deployment and easy customization.</p><p>Unlike traditional enterprise applications designed for use within firewalls, SyntraNet services are built to scale to very large numbers of users and transactions.</p>', :tab_title=>'XML Services',:image=>File.open(root + "/picholder/technology/img_xml_services.png"))
Technology.create(:title=>'Business Process Management and Customizable Workflows', :description=>'<p>SyntraNet proves a powerful standards-based business process management engine to define and manage business processes based on process graphs.  Process graphs support complex workflow patterns and standard patterns can be assembled together to define extremely complex processes.</p><p>Unlike "free-form" process definition languages based on sequencing series of activities, business processes defined with process graphs can be validated and analyzed to detect process problems and bottlenecks.</p><p>SyntraNet provides a library of standard process definitions for administrative, clinical, revenue management, and patient facing workflows.</p>', :tab_title=>'BPM & Workflows',:image=>File.open(root + "/picholder/technology/img_BPM_workflows.png"))
Technology.create(:title=>'Rules Management', :description=>'<p>The SyntraNet rules engineused to implement administrative, clinical and other rulesis based on a full implementation of the RETE pattern-matching algorithm for extremely efficient representation and processing of large sets of rules.</p><p>The RETE algorithm is well-known among designers of rules and inference based systems and is the most efficient algorithm to evaluate and process larger rule sets.</p><p>SyntraNet provides a library of pre-defined rules and the ability to dynamically add and remove rules at run time.</p>', :tab_title=>'Rules',:image=>File.open(root + "/picholder/technology/img_rules.png"))
Technology.create(:title=>'Powerful User Interface Framework', :description=>'<p>An important goal for a new generation of health information technology is to provide user interfaces that are easy to use, interactively rich and extremely productive user on a variety of front-endsbrowsers, desktops, smart phone, pads and other devices.</p><p>SyntraNet uses open standards to provide a powerful user-interface framework to rapidly build and deploy interactive application user interfaces on a variety of front ends with support for multi-touch and emerging surface platform interfaces.</p><p>The user interface framework includes capabilities to build rich internet applications (RIA) targeted at the Flash and Silverlight run times, browser based interfaces using HTML5 frameworks, and native smart client interfaces for smart phones, pads and surfaces.</p>', :tab_title=>'UI Framework',:image=>File.open(root + "/picholder/technology/img_UI_framework-2.png"))
Technology.create(:title=>'Real-Time Collaboration Services', :description=>'<p>To prepare for a new generation of telehealth applications, SyntraNet integrates open real-time collaboration frameworks and tools to provide real-time social interaction and collaboration services for Connected Health applications.  Real time collaboration services include capabilities for chat, whiteboards, webcams, and shared desktops.</p>', :tab_title=>'Collaboration',:image=>File.open(root + "/picholder/technology/img_collaboration.png"))
Technology.create(:title=>'Enterprise Service/Integration Bus', :description=>'<p>SyntraNet includes a highly scalable and powerful enterprise service bus (ESB) with capabilities to integrate applications, business processes and services across a variety of systems.  The ESB architecture is uniquely suited to manage complex interactions among large number of systems.</p><p>The ESB provides a visual programming environment that uses flow compositions to assemble pretested functional blocks to rapidly configure, test and deploy complex integrations between multiple data sources and applications. The ESB is designed for extremely high performance and reliability.</p>', :tab_title=>'ESB',:image=>File.open(root + "/picholder/technology/img_enterprise_bus.png"))



Page.create(:title=>"about")

t = Tag.create(:name=>"Regions")
u = Tag.create(:name=>"science")
v = Tag.create(:name=>"europe")

a = Post.create(:title=>"Kaska people", :content=>"<p>For the ancient Anatolian people, see Kaskians.</p>            <p>The Kaska or Kaska Dena are a First Nations people living mainly in northern British Columbia and the southeastern Yukon in Canada. The Kaska language originally spoken by the Kaska is an Athabaskan language.            Kaska Dena communities and First Nations include:</p>            <ul>            <li>Ross River, Yukon (Ross River Dena Council)</li>            <li>Watson Lake, Yukon and Upper Liard, Yukon (Liard River First Nation)</li>            <li>Good Hope Lake, British Columbia (Dease River First Nation)</li>            <li>Lower Post, British Columbia near Watson Lake (Lower Post First Nation)</li>            <li>Fort Ware, British Columbia (Kwadacha First Nation)</li>            <p>Kaska Dena also live in British Columbia communities of Fireside and Muncho Lake, between Watson Lake and Fort Nelson, British Columbia along the Alaska Highway.</p>            <p>By one account, the name of the asbestos-mining ghost town Cassiar, is believed to be a variant of Kaska, the town being named for the Kaska people; by another account, the word the name Cassiar derives from is a Kaska word either for a black bird, or for the fibrous asbestos ore upon which the town was built.</p>")
b = Post.create(:title=>"Baltic Germans", :content=>"<p>The Baltic Germans (German: Deutsch-Balten, or Baltendeutsche) were mostly ethnically German inhabitants of the eastern shore of the Baltic Sea, which today form the countries of Estonia and Latvia. The Baltic German population never made up more than 10% of the total.[1] They formed the social, commercial, political and cultural elite in that region for several centuries. Some of them also took high positions in the military and civilian life of the Russian Empire, particularly in Saint Petersburg.</p>           <p>In 1881, there were approximately 46,700 Germans in Estonia (5.3% of the population).[2] According to the Russian Empire Census of 1897, there were 120,191 Germans in Latvia, or 6.2% of the population.[3]</p>           <p>In the 12th and 13th centuries[citation needed] Germans, both colonists (see Ostsiedlung) and crusaders, settled in the Baltic.[4] After the Livonian Crusades they quickly came to control all the administrations of government, politics, economics, education and culture of these areas for over 700 years until 1918, despite remaining a minority ethnic group. Whilst the vast majority of urban lands were colonised by traders, rural estates [5] were soon formed by crusaders and their descendants. With the decline of Latin, German quickly became the language of all official documents, commerce and government business for hundreds of years until 1919.</p>           <p>The region was politically subordinated to the rule of the monarchs of Sweden until 1710, and the tsars of the Russian Empire until 1917. Both these successive ruling kingdoms guaranteed the continuation of Baltic Germans' special class privileges and administration rights when they incorporated the provinces into their respective empires.</p>")
c = Post.create(:title=>"Lithuania", :content=>"<p>Estonia (Estonian: Eesti), officially the Republic of Estonia (Estonian: Eesti Vabariik), is a state in the Baltic region of Northern Europe. It is bordered to the north by the Gulf of Finland, to the west by the Baltic Sea, to the south by Latvia (343 km), and to the east by the Lake Peipsi and the Russian Federation (338.6 km).[8] Across the Baltic Sea lies Sweden in the west and Finland in the north. The territory of Estonia covers 45,227 km2 (17,462 sq mi), and is influenced by a temperate seasonal climate. The Estonians are a Finnic people, and the official language, Estonian, is closely related to Finnish.</p><p>Estonia is a democratic parliamentary republic and is divided into 15 counties. The capital and largest city is Tallinn. With a population of 1.34 million, Estonia is one of the least-populous members of the European Union, Eurozone and NATO. Today, Estonia has the highest GDP per person among former Soviet republics.[9] Estonia is listed as a \"High-Income Economy\" by the World Bank, as an \"advanced economy\" by the International Monetary Fund and the country is an OECD member. The United Nations lists Estonia as a developed country with a Human Development Index of \"Very High\".[5] The country is also ranked highly for press freedom, economic freedom, democracy and political freedom and education.</p>")
d = Post.create(:title=>"Temperateness", :content=>"<p>In geography, temperate or tepid latitudes of the globe lie between the tropics and the polar circles. The changes in these regions between summer and winter are generally relatively moderate, rather than extreme hot or cold. However, in certain areas, such as Asia and central North America, the variations between summer and winter can be extreme because these areas are far away from the sea, causing them to have a continental climate. In regions traditionally considered tropical, localities at high altitudes (e.g. parts of the Andes) may have a temperate climate. The north temperate zone extends from the Tropic of Cancer (at about 23.5 degrees north latitude) to the Arctic Circle (at approximately 66.5 degrees north latitude). The south temperate zone extends from the Tropic of Capricorn (at approximately 23.5 degrees south latitude) to the Antarctic Circle (at approximately 66.5 degrees south latitude).</p><p>Within these borders there are many climate types, which are generally grouped into six categories: oceanic (maritime), mediterranean, humid subtropical, continental, arid and semi-arid.</p><p>The maritime climate is affected by the oceans, which help to sustain somewhat stable temperatures throughout the year. In temperate zones the prevailing winds are from the west, thus the western edge of temperate continents most commonly experience this maritime climate. Such regions include Western Europe, and western North America at latitudes between 40 and 60 north (65N in Europe).</p><p>Continental, semi-arid and arid climates are usually situated inland, with warmer summers and colder winters. Heat loss and reception are aided by extensive land mass. In North America, the Rocky Mountains act as a climate barrier to the maritime air blowing from the west, creating a semi-arid and continental climate to the east. In Europe, the maritime climate is able to stabilize inland temperature, because the major mountain range the Alps is oriented east-west (the area east of the long Scandinavian mountain range is an exception).</p>")
e = Post.create(:title=>"Estonia", :content=>"<p>Estonia (Estonian: Eesti), officially the Republic of Estonia (Estonian: Eesti Vabariik), is a state in the Baltic region of Northern Europe. It is bordered to the north by the Gulf of Finland, to the west by the Baltic Sea, to the south by Latvia (343 km), and to the east by the Lake Peipsi and the Russian Federation (338.6 km).[8] Across the Baltic Sea lies Sweden in the west and Finland in the north. The territory of Estonia covers 45,227 km2 (17,462 sq mi), and is influenced by a temperate seasonal climate. The Estonians are a Finnic people, and the official language, Estonian, is closely related to Finnish.</p><p>Estonia is a democratic parliamentary republic and is divided into 15 counties. The capital and largest city is Tallinn. With a population of 1.34 million, Estonia is one of the least-populous members of the European Union, Eurozone and NATO. Today, Estonia has the highest GDP per person among former Soviet republics.[9] Estonia is listed as a \"High-Income Economy\" by the World Bank, as an \"advanced economy\" by the International Monetary Fund and the country is an OECD member. The United Nations lists Estonia as a developed country with a Human Development Index of \"Very High\".[5] The country is also ranked highly for press freedom, economic freedom, democracy and political freedom and education.</p>")
f = Post.create(:title=>"Latvia", :content=>"<p>Estonia (Estonian: Eesti), officially the Republic of Estonia (Estonian: Eesti Vabariik), is a state in the Baltic region of Northern Europe. It is bordered to the north by the Gulf of Finland, to the west by the Baltic Sea, to the south by Latvia (343 km), and to the east by the Lake Peipsi and the Russian Federation (338.6 km).[8] Across the Baltic Sea lies Sweden in the west and Finland in the north. The territory of Estonia covers 45,227 km2 (17,462 sq mi), and is influenced by a temperate seasonal climate. The Estonians are a Finnic people, and the official language, Estonian, is closely related to Finnish.</p><p>Estonia is a democratic parliamentary republic and is divided into 15 counties. The capital and largest city is Tallinn. With a population of 1.34 million, Estonia is one of the least-populous members of the European Union, Eurozone and NATO. Today, Estonia has the highest GDP per person among former Soviet republics.[9] Estonia is listed as a \"High-Income Economy\" by the World Bank, as an \"advanced economy\" by the International Monetary Fund and the country is an OECD member. The United Nations lists Estonia as a developed country with a Human Development Index of \"Very High\".[5] The country is also ranked highly for press freedom, economic freedom, democracy and political freedom and education.</p>")

a.comments << Comment.create(:author=>"John", :content=>"hi there this is so cool", :approved=>1)

t.posts << a
t.posts << b
t.posts << c
t.posts << d
t.posts << e
t.posts << f

u.posts << a
u.posts << d

v.posts << a
v.posts << b
v.posts << c
v.posts << e
v.posts << f
